### ISSUE TITLE
Eukalypse Celery Integration

### ISSUE THREAD

**Issue by oversize** [kinkerl/eukalypse_now#1]
hab gerade mal das eukapyse neu aufgesetzt. Ohne Celery läuft da ja nix. Jetzt kann man ja sagen in den meisten Fällen brauch man eh celery, ok. Aber ich nicht. Ich will einfach bei Lust und Laune den Testrunner nutzen und bestimmte Tests laufen lassen. Reasonable Usecase? 

Ich würde Celery lieber anbieten wenn man mag, aber nicht so wie es im Moment ist integrieren. Ich hab hier angefangen ein paar try/execpts um einige imports zu machen um so das ganze möglichst simpel zu gestalten. Aber der Code der ja letzlich den Screenshot macht ist im Moment in dem Celerytask. Das sollte meiner Meinung nach woanders liegen und dann entweder durch das Mgmt Command oder einen CeleryTask  genutzt werden. 

Das Mgmt Command selber nutzt im Moment den Celerytask. Man könnte das einfach erweitern in dem es daran die Option gibt --task oder andersrum --no-celery o.ä. 

Was meinst du? Einwände?

**Comment by kinkerl** [comment]
ich glaub n "silent" fallback auf ohne celery wäre am schönsten. man schaut nach celery, wenns da ist: gut, wenn nicht dann nicht. im notfall auch n parameter aber wäre nicht ganz so schön. celery sollte default sein. ohne celery bekommt man im live betrieb n paar probleme mit http laufzeiten.

der erstellungscode sollte an die testrun models. da hast du recht!

**Comment by kinkerl** [comment]
verschieb du den code ans model und machst den celery fallback? dann bastel ich gerade weiter an

a) neue stati
b) neues-bild-wird-die-neue-referenz-für-die-zukunft funktion. hab damit schon etwas angefangen.
