### ISSUE TITLE
Identifier Slugification

### ISSUE THREAD

**Issue by oversize** [kinkerl/eukalypse_now#2]
Wenn man einen neuen Test eingibt muss der Identifier ein Slug sein. Bzw schlägt die Validation fehl wenn spaces, umlaute oder sonstwas drin ist. Ich finds total nervig da einen Slug einzugeben. 

Ich würde gerne das Admin den ValidationError abfangen lassen und per slugify(() den String einfach zum Slug machen. Ggfls den User darüber informieren das sich der Wert evtl geändert hat. 

Vieleicht auch einfach ein neues Feld Label (was den Text as is speichert) und das dann in jedem save den identifier neu setzt. Mit Label könnte man etwas freie sein in der Benennung des Screenhots/Tests.

**Comment by kinkerl** [comment]
ok. lass n neues feld label machen
